spring.application.name=spring-boot-config
my.greeting=Hello from config server file
app.name=hiandhello
app.description=This is a sample Spring Boot application ${app.name} that demonstrates the use of externalized configuration properties.
my.list.values=one, two, three, four
my.app.settings={key1: 'value1', key2: 'value2', key3: 'value3'}
db.connection.url=https://github.com/ashishgrwl/ConfigTest
db.connection.username=defaultconfig
db.connection.password=secretconfigserver
db.connection.host=http://localhost:8888/application/default
db.connection.port=9090


