spring.application.name=spring-boot-config
my.greeting=Hello from config server local file
app.name=hiandhello
app.description=This is a sample Spring Boot application ${app.name} that demonstrates the use of externalized configuration properties.
my.list.values=one, two, three, four
my.app.settings={key1: 'value1', key2: 'value2', key3: 'value3'}
db.connection.url=jdbc:mysql://localhost:3306/mydb
db.connection.username=defaultconfig
db.connection.password=secretconfigserver
db.connection.host=localhost
db.connection.port=9090


